version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    env_file:
      - ".env.dist"
    environment:
      PG_PASSWORD: $DB_PASS
      PG_USER: $DB_USER
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env.dist"
    volumes:
      - .:/src
    # Бот стартует после запуска базы
    depends_on:
      - db

# указываются используемые сети
networks:
  botnet:
    # указывается драйвер сети
    driver: bridge